/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AuditRegistry {
  export type BatchAnchorStruct = {
    id: BigNumberish;
    merkleRoot: BytesLike;
    eventCount: BigNumberish;
    timestamp: BigNumberish;
    anchoredBy: AddressLike;
  };

  export type BatchAnchorStructOutput = [
    id: bigint,
    merkleRoot: string,
    eventCount: bigint,
    timestamp: bigint,
    anchoredBy: string
  ] & {
    id: bigint;
    merkleRoot: string;
    eventCount: bigint;
    timestamp: bigint;
    anchoredBy: string;
  };

  export type AuditLogStruct = {
    id: BigNumberish;
    actor: AddressLike;
    action: string;
    resourceId: string;
    detailsHash: string;
    gasFee: BigNumberish;
    timestamp: BigNumberish;
  };

  export type AuditLogStructOutput = [
    id: bigint,
    actor: string,
    action: string,
    resourceId: string,
    detailsHash: string,
    gasFee: bigint,
    timestamp: bigint
  ] & {
    id: bigint;
    actor: string;
    action: string;
    resourceId: string;
    detailsHash: string;
    gasFee: bigint;
    timestamp: bigint;
  };
}

export interface AuditRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ACTION_GAS_FEE"
      | "AUDITOR_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "PAUSER_ROLE"
      | "anchoredRoots"
      | "auditLogs"
      | "batchAnchors"
      | "getBatchAnchor"
      | "getBatchCount"
      | "getLog"
      | "getLogCount"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isRootAnchored"
      | "pause"
      | "paused"
      | "recordBatchRoot"
      | "recordLog"
      | "recordSystemLog"
      | "renounceRole"
      | "revokeRole"
      | "roleManager"
      | "supportsInterface"
      | "totalGasFeesCollected"
      | "unpause"
      | "verifyEventInBatch"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchAnchored"
      | "ContractPaused"
      | "ContractUnpaused"
      | "GasFeeCollected"
      | "LogRecorded"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ACTION_GAS_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "anchoredRoots",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "auditLogs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchAnchors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchAnchor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLog",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLogCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRootAnchored",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordBatchRoot",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordLog",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSystemLog",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalGasFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyEventInBatch",
    values: [BytesLike, BytesLike, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ACTION_GAS_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchoredRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auditLogs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchAnchors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchAnchor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLog", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLogCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRootAnchored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordBatchRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recordLog", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordSystemLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalGasFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyEventInBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace BatchAnchoredEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    merkleRoot: BytesLike,
    eventCount: BigNumberish,
    anchoredBy: AddressLike
  ];
  export type OutputTuple = [
    batchId: bigint,
    merkleRoot: string,
    eventCount: bigint,
    anchoredBy: string
  ];
  export interface OutputObject {
    batchId: bigint;
    merkleRoot: string;
    eventCount: bigint;
    anchoredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractPausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractUnpausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasFeeCollectedEvent {
  export type InputTuple = [actor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [actor: string, amount: bigint];
  export interface OutputObject {
    actor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LogRecordedEvent {
  export type InputTuple = [
    id: BigNumberish,
    actor: AddressLike,
    action: string,
    resourceId: string,
    gasFee: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    actor: string,
    action: string,
    resourceId: string,
    gasFee: bigint
  ];
  export interface OutputObject {
    id: bigint;
    actor: string;
    action: string;
    resourceId: string;
    gasFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuditRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AuditRegistry;
  waitForDeployment(): Promise<this>;

  interface: AuditRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ACTION_GAS_FEE: TypedContractMethod<[], [bigint], "view">;

  AUDITOR_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  anchoredRoots: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  auditLogs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, bigint] & {
        id: bigint;
        actor: string;
        action: string;
        resourceId: string;
        detailsHash: string;
        gasFee: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  batchAnchors: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string] & {
        id: bigint;
        merkleRoot: string;
        eventCount: bigint;
        timestamp: bigint;
        anchoredBy: string;
      }
    ],
    "view"
  >;

  getBatchAnchor: TypedContractMethod<
    [_batchId: BigNumberish],
    [AuditRegistry.BatchAnchorStructOutput],
    "view"
  >;

  getBatchCount: TypedContractMethod<[], [bigint], "view">;

  getLog: TypedContractMethod<
    [_id: BigNumberish],
    [AuditRegistry.AuditLogStructOutput],
    "view"
  >;

  getLogCount: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isRootAnchored: TypedContractMethod<
    [_merkleRoot: BytesLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  recordBatchRoot: TypedContractMethod<
    [_merkleRoot: BytesLike, _eventCount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  recordLog: TypedContractMethod<
    [_action: string, _resourceId: string, _detailsHash: string],
    [bigint],
    "payable"
  >;

  recordSystemLog: TypedContractMethod<
    [_action: string, _resourceId: string, _detailsHash: string],
    [bigint],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  roleManager: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalGasFeesCollected: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifyEventInBatch: TypedContractMethod<
    [
      _merkleRoot: BytesLike,
      _leaf: BytesLike,
      _proof: BytesLike[],
      _leafIndex: BigNumberish
    ],
    [boolean],
    "view"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ACTION_GAS_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "AUDITOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "anchoredRoots"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "auditLogs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, bigint] & {
        id: bigint;
        actor: string;
        action: string;
        resourceId: string;
        detailsHash: string;
        gasFee: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "batchAnchors"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string] & {
        id: bigint;
        merkleRoot: string;
        eventCount: bigint;
        timestamp: bigint;
        anchoredBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBatchAnchor"
  ): TypedContractMethod<
    [_batchId: BigNumberish],
    [AuditRegistry.BatchAnchorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBatchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLog"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [AuditRegistry.AuditLogStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLogCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRootAnchored"
  ): TypedContractMethod<[_merkleRoot: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordBatchRoot"
  ): TypedContractMethod<
    [_merkleRoot: BytesLike, _eventCount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordLog"
  ): TypedContractMethod<
    [_action: string, _resourceId: string, _detailsHash: string],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "recordSystemLog"
  ): TypedContractMethod<
    [_action: string, _resourceId: string, _detailsHash: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalGasFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyEventInBatch"
  ): TypedContractMethod<
    [
      _merkleRoot: BytesLike,
      _leaf: BytesLike,
      _proof: BytesLike[],
      _leafIndex: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BatchAnchored"
  ): TypedContractEvent<
    BatchAnchoredEvent.InputTuple,
    BatchAnchoredEvent.OutputTuple,
    BatchAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "ContractPaused"
  ): TypedContractEvent<
    ContractPausedEvent.InputTuple,
    ContractPausedEvent.OutputTuple,
    ContractPausedEvent.OutputObject
  >;
  getEvent(
    key: "ContractUnpaused"
  ): TypedContractEvent<
    ContractUnpausedEvent.InputTuple,
    ContractUnpausedEvent.OutputTuple,
    ContractUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "GasFeeCollected"
  ): TypedContractEvent<
    GasFeeCollectedEvent.InputTuple,
    GasFeeCollectedEvent.OutputTuple,
    GasFeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "LogRecorded"
  ): TypedContractEvent<
    LogRecordedEvent.InputTuple,
    LogRecordedEvent.OutputTuple,
    LogRecordedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BatchAnchored(uint256,bytes32,uint256,address)": TypedContractEvent<
      BatchAnchoredEvent.InputTuple,
      BatchAnchoredEvent.OutputTuple,
      BatchAnchoredEvent.OutputObject
    >;
    BatchAnchored: TypedContractEvent<
      BatchAnchoredEvent.InputTuple,
      BatchAnchoredEvent.OutputTuple,
      BatchAnchoredEvent.OutputObject
    >;

    "ContractPaused(address)": TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;
    ContractPaused: TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;

    "ContractUnpaused(address)": TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;
    ContractUnpaused: TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;

    "GasFeeCollected(address,uint256)": TypedContractEvent<
      GasFeeCollectedEvent.InputTuple,
      GasFeeCollectedEvent.OutputTuple,
      GasFeeCollectedEvent.OutputObject
    >;
    GasFeeCollected: TypedContractEvent<
      GasFeeCollectedEvent.InputTuple,
      GasFeeCollectedEvent.OutputTuple,
      GasFeeCollectedEvent.OutputObject
    >;

    "LogRecorded(uint256,address,string,string,uint256)": TypedContractEvent<
      LogRecordedEvent.InputTuple,
      LogRecordedEvent.OutputTuple,
      LogRecordedEvent.OutputObject
    >;
    LogRecorded: TypedContractEvent<
      LogRecordedEvent.InputTuple,
      LogRecordedEvent.OutputTuple,
      LogRecordedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
