/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AuditRegistry {
  export type AuditLogStruct = {
    id: BigNumberish;
    actor: AddressLike;
    action: string;
    resourceId: string;
    detailsHash: string;
    timestamp: BigNumberish;
  };

  export type AuditLogStructOutput = [
    id: bigint,
    actor: string,
    action: string,
    resourceId: string,
    detailsHash: string,
    timestamp: bigint
  ] & {
    id: bigint;
    actor: string;
    action: string;
    resourceId: string;
    detailsHash: string;
    timestamp: bigint;
  };
}

export interface AuditRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auditLogs"
      | "getLog"
      | "getLogCount"
      | "owner"
      | "recordLog"
      | "renounceOwnership"
      | "roleManager"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LogRecorded" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "auditLogs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLog",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLogCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordLog",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "auditLogs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLog", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLogCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordLog", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace LogRecordedEvent {
  export type InputTuple = [
    id: BigNumberish,
    actor: AddressLike,
    action: string,
    resourceId: string
  ];
  export type OutputTuple = [
    id: bigint,
    actor: string,
    action: string,
    resourceId: string
  ];
  export interface OutputObject {
    id: bigint;
    actor: string;
    action: string;
    resourceId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuditRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AuditRegistry;
  waitForDeployment(): Promise<this>;

  interface: AuditRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auditLogs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint] & {
        id: bigint;
        actor: string;
        action: string;
        resourceId: string;
        detailsHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getLog: TypedContractMethod<
    [_id: BigNumberish],
    [AuditRegistry.AuditLogStructOutput],
    "view"
  >;

  getLogCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordLog: TypedContractMethod<
    [_action: string, _resourceId: string, _detailsHash: string],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  roleManager: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auditLogs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint] & {
        id: bigint;
        actor: string;
        action: string;
        resourceId: string;
        detailsHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLog"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [AuditRegistry.AuditLogStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLogCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordLog"
  ): TypedContractMethod<
    [_action: string, _resourceId: string, _detailsHash: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "LogRecorded"
  ): TypedContractEvent<
    LogRecordedEvent.InputTuple,
    LogRecordedEvent.OutputTuple,
    LogRecordedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "LogRecorded(uint256,address,string,string)": TypedContractEvent<
      LogRecordedEvent.InputTuple,
      LogRecordedEvent.OutputTuple,
      LogRecordedEvent.OutputObject
    >;
    LogRecorded: TypedContractEvent<
      LogRecordedEvent.InputTuple,
      LogRecordedEvent.OutputTuple,
      LogRecordedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
