/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IdentityRecoveryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "DEFAULT_EXPIRY_DURATION"
      | "MAX_GUARDIANS"
      | "MIN_GUARDIANS"
      | "RECOVERY_EXECUTOR_ROLE"
      | "TIMELOCK_DURATION"
      | "addGuardian"
      | "approveRecovery"
      | "cancelRecovery"
      | "checkIsGuardian"
      | "executeRecovery"
      | "getGuardianCount"
      | "getGuardians"
      | "getRecoveryRequest"
      | "getRoleAdmin"
      | "grantRole"
      | "guardians"
      | "hasApproved"
      | "hasRejected"
      | "hasRole"
      | "identityNFT"
      | "initiateRecovery"
      | "isGuardian"
      | "recoveryRequests"
      | "rejectRecovery"
      | "removeGuardian"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GuardianAdded"
      | "GuardianRemoved"
      | "RecoveryApproved"
      | "RecoveryCancelled"
      | "RecoveryExecuted"
      | "RecoveryRejected"
      | "RecoveryRequested"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_EXPIRY_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_GUARDIANS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_GUARDIANS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RECOVERY_EXECUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIMELOCK_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addGuardian",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveRecovery",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRecovery",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIsGuardian",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeRecovery",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardianCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardians",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecoveryRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "guardians",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApproved",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRejected",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initiateRecovery",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isGuardian",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoveryRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectRecovery",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeGuardian",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_EXPIRY_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_GUARDIANS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_GUARDIANS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RECOVERY_EXECUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIMELOCK_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardianCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardians",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecoveryRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "guardians", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasRejected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isGuardian", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoveryRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace GuardianAddedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    guardian: AddressLike,
    addedBy: AddressLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    guardian: string,
    addedBy: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    guardian: string;
    addedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuardianRemovedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    guardian: AddressLike,
    removedBy: AddressLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    guardian: string,
    removedBy: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    guardian: string;
    removedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryApprovedEvent {
  export type InputTuple = [requestId: BytesLike, guardian: AddressLike];
  export type OutputTuple = [requestId: string, guardian: string];
  export interface OutputObject {
    requestId: string;
    guardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryCancelledEvent {
  export type InputTuple = [requestId: BytesLike, cancelledBy: AddressLike];
  export type OutputTuple = [requestId: string, cancelledBy: string];
  export interface OutputObject {
    requestId: string;
    cancelledBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryExecutedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    tokenId: BigNumberish,
    oldWallet: AddressLike,
    newWallet: AddressLike
  ];
  export type OutputTuple = [
    requestId: string,
    tokenId: bigint,
    oldWallet: string,
    newWallet: string
  ];
  export interface OutputObject {
    requestId: string;
    tokenId: bigint;
    oldWallet: string;
    newWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryRejectedEvent {
  export type InputTuple = [requestId: BytesLike, guardian: AddressLike];
  export type OutputTuple = [requestId: string, guardian: string];
  export interface OutputObject {
    requestId: string;
    guardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryRequestedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    tokenId: BigNumberish,
    oldWallet: AddressLike,
    newWallet: AddressLike,
    requiredApprovals: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    tokenId: bigint,
    oldWallet: string,
    newWallet: string,
    requiredApprovals: bigint
  ];
  export interface OutputObject {
    requestId: string;
    tokenId: bigint;
    oldWallet: string;
    newWallet: string;
    requiredApprovals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IdentityRecovery extends BaseContract {
  connect(runner?: ContractRunner | null): IdentityRecovery;
  waitForDeployment(): Promise<this>;

  interface: IdentityRecoveryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_EXPIRY_DURATION: TypedContractMethod<[], [bigint], "view">;

  MAX_GUARDIANS: TypedContractMethod<[], [bigint], "view">;

  MIN_GUARDIANS: TypedContractMethod<[], [bigint], "view">;

  RECOVERY_EXECUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  TIMELOCK_DURATION: TypedContractMethod<[], [bigint], "view">;

  addGuardian: TypedContractMethod<
    [tokenId: BigNumberish, guardian: AddressLike],
    [void],
    "nonpayable"
  >;

  approveRecovery: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  cancelRecovery: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  checkIsGuardian: TypedContractMethod<
    [tokenId: BigNumberish, guardian: AddressLike],
    [boolean],
    "view"
  >;

  executeRecovery: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  getGuardianCount: TypedContractMethod<
    [tokenId: BigNumberish],
    [bigint],
    "view"
  >;

  getGuardians: TypedContractMethod<
    [tokenId: BigNumberish],
    [string[]],
    "view"
  >;

  getRecoveryRequest: TypedContractMethod<
    [requestId: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        oldWallet: string;
        newWallet: string;
        tokenId: bigint;
        requiredApprovals: bigint;
        approvalCount: bigint;
        rejectionCount: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        timelockExpires: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  guardians: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  hasApproved: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasRejected: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  identityNFT: TypedContractMethod<[], [string], "view">;

  initiateRecovery: TypedContractMethod<
    [
      tokenId: BigNumberish,
      newWallet: AddressLike,
      requiredApprovals: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  isGuardian: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  recoveryRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        oldWallet: string;
        newWallet: string;
        tokenId: bigint;
        requiredApprovals: bigint;
        approvalCount: bigint;
        rejectionCount: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        timelockExpires: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  rejectRecovery: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  removeGuardian: TypedContractMethod<
    [tokenId: BigNumberish, guardian: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_EXPIRY_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_GUARDIANS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_GUARDIANS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RECOVERY_EXECUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TIMELOCK_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addGuardian"
  ): TypedContractMethod<
    [tokenId: BigNumberish, guardian: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveRecovery"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelRecovery"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkIsGuardian"
  ): TypedContractMethod<
    [tokenId: BigNumberish, guardian: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeRecovery"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getGuardianCount"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGuardians"
  ): TypedContractMethod<[tokenId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRecoveryRequest"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        oldWallet: string;
        newWallet: string;
        tokenId: bigint;
        requiredApprovals: bigint;
        approvalCount: bigint;
        rejectionCount: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        timelockExpires: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "guardians"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasApproved"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRejected"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initiateRecovery"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      newWallet: AddressLike,
      requiredApprovals: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isGuardian"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "recoveryRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        oldWallet: string;
        newWallet: string;
        tokenId: bigint;
        requiredApprovals: bigint;
        approvalCount: bigint;
        rejectionCount: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        timelockExpires: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rejectRecovery"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeGuardian"
  ): TypedContractMethod<
    [tokenId: BigNumberish, guardian: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "GuardianAdded"
  ): TypedContractEvent<
    GuardianAddedEvent.InputTuple,
    GuardianAddedEvent.OutputTuple,
    GuardianAddedEvent.OutputObject
  >;
  getEvent(
    key: "GuardianRemoved"
  ): TypedContractEvent<
    GuardianRemovedEvent.InputTuple,
    GuardianRemovedEvent.OutputTuple,
    GuardianRemovedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryApproved"
  ): TypedContractEvent<
    RecoveryApprovedEvent.InputTuple,
    RecoveryApprovedEvent.OutputTuple,
    RecoveryApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryCancelled"
  ): TypedContractEvent<
    RecoveryCancelledEvent.InputTuple,
    RecoveryCancelledEvent.OutputTuple,
    RecoveryCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryExecuted"
  ): TypedContractEvent<
    RecoveryExecutedEvent.InputTuple,
    RecoveryExecutedEvent.OutputTuple,
    RecoveryExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryRejected"
  ): TypedContractEvent<
    RecoveryRejectedEvent.InputTuple,
    RecoveryRejectedEvent.OutputTuple,
    RecoveryRejectedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryRequested"
  ): TypedContractEvent<
    RecoveryRequestedEvent.InputTuple,
    RecoveryRequestedEvent.OutputTuple,
    RecoveryRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "GuardianAdded(uint256,address,address)": TypedContractEvent<
      GuardianAddedEvent.InputTuple,
      GuardianAddedEvent.OutputTuple,
      GuardianAddedEvent.OutputObject
    >;
    GuardianAdded: TypedContractEvent<
      GuardianAddedEvent.InputTuple,
      GuardianAddedEvent.OutputTuple,
      GuardianAddedEvent.OutputObject
    >;

    "GuardianRemoved(uint256,address,address)": TypedContractEvent<
      GuardianRemovedEvent.InputTuple,
      GuardianRemovedEvent.OutputTuple,
      GuardianRemovedEvent.OutputObject
    >;
    GuardianRemoved: TypedContractEvent<
      GuardianRemovedEvent.InputTuple,
      GuardianRemovedEvent.OutputTuple,
      GuardianRemovedEvent.OutputObject
    >;

    "RecoveryApproved(bytes32,address)": TypedContractEvent<
      RecoveryApprovedEvent.InputTuple,
      RecoveryApprovedEvent.OutputTuple,
      RecoveryApprovedEvent.OutputObject
    >;
    RecoveryApproved: TypedContractEvent<
      RecoveryApprovedEvent.InputTuple,
      RecoveryApprovedEvent.OutputTuple,
      RecoveryApprovedEvent.OutputObject
    >;

    "RecoveryCancelled(bytes32,address)": TypedContractEvent<
      RecoveryCancelledEvent.InputTuple,
      RecoveryCancelledEvent.OutputTuple,
      RecoveryCancelledEvent.OutputObject
    >;
    RecoveryCancelled: TypedContractEvent<
      RecoveryCancelledEvent.InputTuple,
      RecoveryCancelledEvent.OutputTuple,
      RecoveryCancelledEvent.OutputObject
    >;

    "RecoveryExecuted(bytes32,uint256,address,address)": TypedContractEvent<
      RecoveryExecutedEvent.InputTuple,
      RecoveryExecutedEvent.OutputTuple,
      RecoveryExecutedEvent.OutputObject
    >;
    RecoveryExecuted: TypedContractEvent<
      RecoveryExecutedEvent.InputTuple,
      RecoveryExecutedEvent.OutputTuple,
      RecoveryExecutedEvent.OutputObject
    >;

    "RecoveryRejected(bytes32,address)": TypedContractEvent<
      RecoveryRejectedEvent.InputTuple,
      RecoveryRejectedEvent.OutputTuple,
      RecoveryRejectedEvent.OutputObject
    >;
    RecoveryRejected: TypedContractEvent<
      RecoveryRejectedEvent.InputTuple,
      RecoveryRejectedEvent.OutputTuple,
      RecoveryRejectedEvent.OutputObject
    >;

    "RecoveryRequested(bytes32,uint256,address,address,uint256)": TypedContractEvent<
      RecoveryRequestedEvent.InputTuple,
      RecoveryRequestedEvent.OutputTuple,
      RecoveryRequestedEvent.OutputObject
    >;
    RecoveryRequested: TypedContractEvent<
      RecoveryRequestedEvent.InputTuple,
      RecoveryRequestedEvent.OutputTuple,
      RecoveryRequestedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
